# Site wide configuration

title:            pita irul sayekti
locale:           en_US
#url:              http://localhost:4000
url:              http://pitairulsayekti.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Pita Irul Sayekti
  avatar: bio-photo.jpg
  bio:
  Nama : pita Irul Sayekti
  TTL : Sarigaluh, 10 Juni 1995
  Alamat : Jl. Perum Villa Sentosa
  Kelas : SIF A
  Jurusan : http://sif.uin-suska.ac.id/
  Fakultas : http://fst.uin-suska.ac.id/
  Universitas : http://uin-suska.ac.id/
  email: 
  disqus-shortname: 
  twitter: pita_iruL #username
  facebook: pita irul sayekti #username
  google:
    plus: pita irul #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: pitairulsayekti #username
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
